### ISSUE TITLE
The bare/config files are inconsistent with themselves and the buildbarn applications

### ISSUE THREAD

**Issue by YngveNPettersen** [buildbarn/bb-deployments#16] opened 2020-01-18 21:23 UTC
The new config jsonnet files in the bare deployment example are inconsistent with themselves, for example referencing "blobstore.clientBlobstore" rather than the correct "blobstore.client_blobstore" entry. Other examples are all the metrics references.

Once those are fixed, the resulting json files are not acceptable to the various bb-applications because the resulting files contain entries that are "unknown", for example bb_event_service complain about "grpc.GRPCClientConfiguration.endpoint".

Also, the run.sh script assumes that the json files are in the config directory, but the current state is that it only contain jsonnet files, which means that the script will need to add a jsonnet -> json conversion to be usable out of the box.

**Comment by EdSchouten** [comment] 2020-01-18 21:25
Duplicate of: #10

**Closed by EdSchouten** 2020-01-18 21:25 UTC
