### ISSUE TITLE
bazel build not completing because of worker missing

### ISSUE THREAD

**Issue by dhillondeep** [buildbarn/bb-deployments#40] opened 2020-07-27 04:55 UTC
Sometimes #39 issue is not there and `docker-compose` works without any warnings. In that case, when I try to build using bazel, I run into following:
```
INFO: Invocation ID: ccdc75c7-6884-4795-a2c8-13a572417bd0
DEBUG: /root/.cache/bazel/_bazel_root/8c069df52082beee3c95ca17836fb8e2/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:14:
Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.
DEBUG: /root/.cache/bazel/_bazel_root/8c069df52082beee3c95ca17836fb8e2/external/bazel_toolchains/rules/rbe_repo.bzl:491:10: Bazel 3.4.1 is used in rbe_default.
INFO: Analyzed target //main:hello-world (17 packages loaded, 53 targets configured).
INFO: Found 1 target...
ERROR: /app/main/BUILD:3:10: C++ compilation of rule '//main:hello-world' failed (Exit 34). Note: Remote connection/protocol failed with: execution failed catastrophically UNAVAILABLE: No workers exist for instance "remote-execution" platform {"properties":[{"name":"OSFamily","value":"Linux"},{"name":"container-image","value":"docker://marketplace.gcr.io/google/rbe-ubuntu16-04@sha256:1a8ed713f40267bb51fe17de012fa631a20c52df818ccb317aaed2ee068dfc61"}]}
Target //main:hello-world failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 7.582s, Critical Path: 3.32s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```

I ran command:
```
 bazel build --config=mycluster-ubuntu16-04 //...
```

**Comment by EdSchouten** [comment] 2020-07-27 05:56
Duplicate of https://github.com/buildbarn/bb-deployments/issues/24

**Closed by EdSchouten** 2020-07-27 05:56 UTC
