### ISSUE TITLE
how to modifying referenced container image  in kubernetes deployment

### ISSUE THREAD

**Issue by ivanthelad** [buildbarn/bb-deployments#15] opened 2020-01-14 15:20 UTC
Hi, 
I'm new to Bazel and I'm testing the kubernetes deployment ontop of a cluster( Azure AKS). Unfortunately the  remote instance is always trying to start instances of containers based on the rbe images from  gcr.io. which are only accessible if i prepull the images on the target hosts. it should be possible to reference the buildbarn images rbe images (https://hub.docker.com/r/buildbarn/bb-runner-ubuntu16-04), right? i would like to avoid prepulling the images. 

i have modified the following config to point to the publicly available buildbarn image instead
https://github.com/Qinusty/bb-deployments/blob/qinusty/fix-k8s-deploy/kubernetes/config/worker-ubuntu16-04.yaml#L27

is there any additional steps required to get a remote environment on kubernetes up and running

The error i receive is.

`ARNING: option '--remote_instance_name' was expanded to from both option '--config=mycluster-ubuntu16-04' (source command line options) and option '--config=mycluster-ubuntu16-04' (source command line options)
WARNING: option '--remote_instance_name' was expanded to from both option '--config=mycluster-ubuntu16-04' (source command line options) and option '--config=mycluster-ubuntu16-04' (source command line options)
INFO: Invocation ID: c8ec811a-32b4-49fb-ae1b-a758318c1a99
INFO: Streaming build results to: http://xxxxx/build_events/bb-event-service/c8ec811a-32b4-49fb-ae1b-a758318c1a99
INFO: Analyzed 331 targets (44 packages loaded, 1757 targets configured).
INFO: Found 331 targets...
INFO: Deleting stale sandbox base /home/ivan/.cache/bazel/_bazel_root/5ca4ca104c78138db28b17b8a63ba397/sandbox
ERROR: /home/ivan/Source/abseil-cpp/absl/base/BUILD.bazel:177:1: C++ compilation of rule '//absl/base:base' failed (Exit 34). Note: Remote connection/protocol failed with: execution failed FAILED_PRECONDITION: No workers exist for instance "remote-execution" platform {"properties":[{"name":"container-image","value":"docker://marketplace.gcr.io/google/rbe-ubuntu16-04@sha256:da0f21c71abce3bbb92c3a0c44c3737f007a82b60f8bd2930abc55fe64fc2729"}]}
INFO: Elapsed time: 12.867s, Critical Path: 0.95s
INFO: 0 processes.
INFO: Streaming build results to: http://xxxxxxx/build_events/bb-event-service/c8ec811a-32b4-49fb-ae1b-a758318c1a99
FAILED: Build did NOT complete successfully`

**Comment by EdSchouten** [comment] 2020-03-14 12:35
Sorry for not commenting to this at the time. This came in during my vacation and dropped off the radar ever since. To debug issues like these, you can always visit the web service exposed by bb-scheduler. That one will show you which platform queues are actually registered.

- If this shows a page with empty tables, it means that workers aren't properly connected to your scheduler.
- If there are workers there, but they don't match up with what's shown in the error message, it means you need to adjust your workers or the settings of your Bazel client.

Final note: Keep in mind that if you make changes to Kubernetes config maps, it doesn't mean that pods that use them are automatically restarted.

Hopefully you were able to root cause this issue in January. Again, my apologies for the delayed response. I will close this issue, as the question that was asked has been answered. Feel free to reopen if necessary.

**Closed by EdSchouten** 2020-03-14 12:35 UTC
